services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ardahan91185.
      POSTGRES_DB: enigmadb
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://postgres:Ardahan91185.@db:5432/enigmadb
    
    depends_on:
      - db
    
    
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx konfigürasyon dosyası
      
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always
    networks:
      - default